name: Build and Commit Games CSV

on:
  workflow_dispatch:

permissions:
  contents: write   # allow commit/push

jobs:
  build-games:
    runs-on: ubuntu-latest
    env:
      WEATHERAPI_KEY: ${{ secrets.WEATHERAPI_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-dateutil

      - name: Run builder script
        run: python src/build_games_csv.py

      - name: Commit and push updated games.csv
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/processed/games.csv
          git commit -m "Automated update: games.csv" || echo "No changes to commit"
          git push
