name: Build unified team dataset

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pandas numpy

      - name: Build unified dataset (team_stats only)
        run: |
          python src/build_unified_dataset.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/processed/nfl_unified_with_metrics.csv || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: rebuild unified team dataset"
            git push
          else
            echo "No changes to commit."
          fi
