name: Convert dumps to CSV and push

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  convert-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pandas

      - name: Convert dumps to CSV
        run: |
          python src/convert_dumps_to_csv.py

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/raw || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: convert dumps to CSV and update data/raw"
            git push
          else
            echo "No changes to commit."
          fi
