name: Normalize Teams

on:
  workflow_dispatch:

jobs:
  normalize:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pandas
        run: pip install pandas

      - name: Run normalization script
        run: python src/normalize_teams.py

      - name: Force commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Auto-normalized team names" || echo "No changes"
          git push --force
