name: Run Player Projections

on:
  workflow_dispatch:

permissions:
  contents: write   # allow commit/push

jobs:
  player-projections:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-dateutil

      - name: Run player projections script
        run: python src/player_projections.py

      - name: Commit and push player_projections.csv
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/processed/player_projections.csv
          git commit -m "Automated update: player_projections.csv" || echo "No changes to commit"
          git push
